---
# tasks file for nginx
- name: apt update
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
  notify: 
    - restart nginx

- name: copy template to nginx folder
  ansible.builtin.template:
    src: nginx_template.j2
    dest: /etc/nginx/nginx.conf 
  notify:
    - reload nginx
  tags:
  - nginx-configuration

